[[colors.indexed_colors]]
color = "0xcb4b16"
index = 16

[[colors.indexed_colors]]
color = "0xd33682"
index = 17

[[colors.indexed_colors]]
color = "0x073642"
index = 18

[[colors.indexed_colors]]
color = "0x586e75"
index = 19

[[colors.indexed_colors]]
color = "0x839496"
index = 20

[[colors.indexed_colors]]
color = "0xeee8d5"
index = 21

[colors.bright]
black = "0x2d3437"
blue = "0x71baf2"
cyan = "0x67cbe7"
green = "0x96d988"
magenta = "0xce89df"
red = "0xef7e7e"
white = "0xbdc3c2"
yellow = "0xf4d67a"

[colors.normal]
black = "0x232a2d"
blue = "0x67b0e8"
cyan = "0x6cbfbf"
green = "0x8ccf7e"
magenta = "0xc47fd5"
red = "0xe57474"
white = "0xb3b9b8"
yellow = "0xe5c76b"

[colors.primary]
background = "0x141b1e"
foreground = "0xdadada"

[env]
TERM = "xterm-256color"

[font]
size = 9.5

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[scrolling]
history = 4096
multiplier = 3

[window]
decorations = "none"
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 3
y = 4
